name: dom_util
description: Utilities for working with DOM.
version: 0.1.0
#author: Your Name <email@example.com>
homepage: https://github.com/fluidic/dom_util

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
